version: '3.3'

services:
  app:
    build:
      context: .
    container_name: about-alodi
    labels:
      - 'log.level=DEBUG'
      - 'traefik.enable=true'
      - 'traefik.http.routers.about-alodi.entrypoints=websecure'
      - 'traefik.http.routers.about-alodi.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.about-alodi.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.about-alodi.tls.domains[0].main=${DOMAIN}'
      - 'traefik.http.services.app-elements.loadbalancer.server.port=80'
    networks:
      - 'traefik-global-proxy'
    ports:
      - '8888:80'

networks:
  traefik-global-proxy:
    external: true
