version: '3'

services:
  app:
    build:
      context: .
    container_name: about-alodi
    ports:
      - '80:80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.about-alodi.rule=Host(`about.${DOMAIN}`)'
      - 'traefik.http.routers.about-alodi.entrypoints=web-secure'
